"""Built-in site templates (30+ domains) for agent guidance."""

from __future__ import annotations

from app.sites.models import SiteTemplate

SOCIAL_STEPS = (
    "Navigate to discover/trending sections",
    "Collect entity cards and ranking metadata",
    "Normalize output into a structured list",
)
NEWS_STEPS = (
    "Navigate to front page or section hubs",
    "Extract headline cards with links and timestamps",
    "Optionally follow article links for summaries",
)
DOC_STEPS = (
    "Navigate to docs or index pages",
    "Extract headings, navigation links, and metadata",
    "Return concise structured documentation map",
)


SITE_TEMPLATES: tuple[SiteTemplate, ...] = (
    SiteTemplate(
        site_id="github",
        name="GitHub",
        domains=("github.com",),
        aliases=("github", "repo", "repositories"),
        default_strategy="github_repository_extraction",
        extraction_goal="repositories",
        navigation_steps=(
            "Navigate to Explore/Trending/Search pages",
            "Extract repository metadata and links",
            "Format repository rows for csv/json output",
        ),
        output_fields=("username", "repo_name", "stars", "forks", "url"),
        target_urls=("https://github.com/explore", "https://github.com/trending"),
        description="Code repositories, projects, and trend pages",
    ),
    SiteTemplate(
        site_id="reddit",
        name="Reddit",
        domains=("reddit.com", "old.reddit.com"),
        aliases=("reddit", "subreddit", "communities"),
        default_strategy="reddit_community_extraction",
        extraction_goal="communities",
        navigation_steps=(
            "Navigate to community discovery/popular endpoints",
            "Handle anti-bot challenge fallback if required",
            "Return normalized subreddit rows",
        ),
        output_fields=("subreddit", "title", "subscribers", "active_users", "url"),
        target_urls=("https://www.reddit.com/", "https://www.reddit.com/subreddits/popular"),
        description="Communities, posts, and subreddit metadata",
    ),
    SiteTemplate(
        site_id="x",
        name="X (Twitter)",
        domains=("x.com", "twitter.com"),
        aliases=("x", "twitter", "tweets"),
        extraction_goal="posts",
        navigation_steps=SOCIAL_STEPS,
        output_fields=("author", "post_text", "likes", "replies", "url"),
        target_urls=("https://x.com/explore",),
        description="Short-form social posts and trends",
    ),
    SiteTemplate(
        site_id="youtube",
        name="YouTube",
        domains=("youtube.com", "youtu.be"),
        aliases=("youtube", "videos", "channels"),
        extraction_goal="videos",
        navigation_steps=SOCIAL_STEPS,
        output_fields=("title", "channel", "views", "published", "url"),
        target_urls=("https://www.youtube.com/feed/trending",),
        description="Video listings, channels, and trend feeds",
    ),
    SiteTemplate(
        site_id="instagram",
        name="Instagram",
        domains=("instagram.com",),
        aliases=("instagram", "reels", "posts"),
        extraction_goal="social_posts",
        navigation_steps=SOCIAL_STEPS,
        output_fields=("author", "caption", "likes", "comments", "url"),
        target_urls=("https://www.instagram.com/explore/",),
        description="Photo/video social feed extraction",
    ),
    SiteTemplate(
        site_id="facebook",
        name="Facebook",
        domains=("facebook.com", "fb.com"),
        aliases=("facebook", "pages", "groups"),
        extraction_goal="social_posts",
        navigation_steps=SOCIAL_STEPS,
        output_fields=("page", "post_text", "reactions", "comments", "url"),
        target_urls=("https://www.facebook.com/watch/",),
        description="Pages, groups, and social content",
    ),
    SiteTemplate(
        site_id="linkedin",
        name="LinkedIn",
        domains=("linkedin.com",),
        aliases=("linkedin", "jobs", "companies"),
        extraction_goal="professional_content",
        navigation_steps=SOCIAL_STEPS,
        output_fields=("title", "company", "location", "engagement", "url"),
        target_urls=("https://www.linkedin.com/feed/",),
        description="Professional posts, companies, and jobs",
    ),
    SiteTemplate(
        site_id="tiktok",
        name="TikTok",
        domains=("tiktok.com",),
        aliases=("tiktok", "shorts", "videos"),
        extraction_goal="videos",
        navigation_steps=SOCIAL_STEPS,
        output_fields=("creator", "caption", "likes", "comments", "url"),
        target_urls=("https://www.tiktok.com/trending",),
        description="Short video trend discovery",
    ),
    SiteTemplate(
        site_id="medium",
        name="Medium",
        domains=("medium.com",),
        aliases=("medium", "blogs", "articles"),
        extraction_goal="articles",
        navigation_steps=NEWS_STEPS,
        output_fields=("title", "author", "claps", "reading_time", "url"),
        target_urls=("https://medium.com/tag/technology",),
        description="Article/blog extraction",
    ),
    SiteTemplate(
        site_id="devto",
        name="DEV Community",
        domains=("dev.to",),
        aliases=("devto", "dev.to", "developer posts"),
        extraction_goal="articles",
        navigation_steps=NEWS_STEPS,
        output_fields=("title", "author", "reactions", "comments", "url"),
        target_urls=("https://dev.to/top/week",),
        description="Developer articles and posts",
    ),
    SiteTemplate(
        site_id="stackoverflow",
        name="Stack Overflow",
        domains=("stackoverflow.com",),
        aliases=("stackoverflow", "questions", "answers"),
        extraction_goal="questions",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "votes", "answers", "tags", "url"),
        target_urls=("https://stackoverflow.com/questions",),
        description="Q&A extraction",
    ),
    SiteTemplate(
        site_id="kaggle",
        name="Kaggle",
        domains=("kaggle.com",),
        aliases=("kaggle", "datasets", "competitions"),
        extraction_goal="datasets",
        navigation_steps=DOC_STEPS,
        output_fields=("dataset_name", "author", "votes", "updated", "url"),
        target_urls=("https://www.kaggle.com/datasets",),
        description="Dataset and competition listings",
    ),
    SiteTemplate(
        site_id="huggingface",
        name="Hugging Face",
        domains=("huggingface.co",),
        aliases=("huggingface", "models", "spaces"),
        extraction_goal="models",
        navigation_steps=DOC_STEPS,
        output_fields=("model_id", "downloads", "likes", "task", "url"),
        target_urls=("https://huggingface.co/models",),
        description="Model and dataset hubs",
    ),
    SiteTemplate(
        site_id="arxiv",
        name="arXiv",
        domains=("arxiv.org",),
        aliases=("arxiv", "papers", "preprints"),
        extraction_goal="papers",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "authors", "category", "published", "url"),
        target_urls=("https://arxiv.org/list/cs/new",),
        description="Research paper listings",
    ),
    SiteTemplate(
        site_id="wikipedia",
        name="Wikipedia",
        domains=("wikipedia.org",),
        aliases=("wikipedia", "wiki", "encyclopedia"),
        extraction_goal="reference_content",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "summary", "sections", "references", "url"),
        target_urls=("https://en.wikipedia.org/wiki/Main_Page",),
        description="Reference and encyclopedia pages",
    ),
    SiteTemplate(
        site_id="pypi",
        name="PyPI",
        domains=("pypi.org",),
        aliases=("pypi", "python packages"),
        extraction_goal="packages",
        navigation_steps=DOC_STEPS,
        output_fields=("package", "version", "downloads", "license", "url"),
        target_urls=("https://pypi.org/search/",),
        description="Python package metadata",
    ),
    SiteTemplate(
        site_id="npm",
        name="npm",
        domains=("npmjs.com",),
        aliases=("npm", "node packages"),
        extraction_goal="packages",
        navigation_steps=DOC_STEPS,
        output_fields=("package", "version", "weekly_downloads", "maintainers", "url"),
        target_urls=("https://www.npmjs.com/search",),
        description="Node package metadata",
    ),
    SiteTemplate(
        site_id="producthunt",
        name="Product Hunt",
        domains=("producthunt.com",),
        aliases=("product hunt", "launches", "products"),
        extraction_goal="products",
        navigation_steps=SOCIAL_STEPS,
        output_fields=("product", "tagline", "votes", "category", "url"),
        target_urls=("https://www.producthunt.com/",),
        description="New product launch listings",
    ),
    SiteTemplate(
        site_id="hackernews",
        name="Hacker News",
        domains=("news.ycombinator.com",),
        aliases=("hackernews", "hn", "top stories"),
        extraction_goal="stories",
        navigation_steps=NEWS_STEPS,
        output_fields=("title", "points", "comments", "author", "url"),
        target_urls=("https://news.ycombinator.com/",),
        description="Tech news headlines",
    ),
    SiteTemplate(
        site_id="substack",
        name="Substack",
        domains=("substack.com",),
        aliases=("substack", "newsletters"),
        extraction_goal="newsletter_posts",
        navigation_steps=NEWS_STEPS,
        output_fields=("title", "author", "publication", "published", "url"),
        target_urls=("https://substack.com/discover",),
        description="Newsletter and long-form posts",
    ),
    SiteTemplate(
        site_id="quora",
        name="Quora",
        domains=("quora.com",),
        aliases=("quora", "questions"),
        extraction_goal="questions",
        navigation_steps=DOC_STEPS,
        output_fields=("question", "answer_count", "followers", "topic", "url"),
        target_urls=("https://www.quora.com/",),
        description="Question and answer listings",
    ),
    SiteTemplate(
        site_id="pinterest",
        name="Pinterest",
        domains=("pinterest.com",),
        aliases=("pinterest", "pins", "boards"),
        extraction_goal="pins",
        navigation_steps=SOCIAL_STEPS,
        output_fields=("title", "board", "saves", "author", "url"),
        target_urls=("https://www.pinterest.com/",),
        description="Pins and board discovery",
    ),
    SiteTemplate(
        site_id="imdb",
        name="IMDb",
        domains=("imdb.com",),
        aliases=("imdb", "movies", "tv"),
        extraction_goal="titles",
        navigation_steps=NEWS_STEPS,
        output_fields=("title", "year", "rating", "genres", "url"),
        target_urls=("https://www.imdb.com/chart/",),
        description="Movie and TV listings",
    ),
    SiteTemplate(
        site_id="nytimes",
        name="New York Times",
        domains=("nytimes.com",),
        aliases=("new york times", "nyt"),
        extraction_goal="news_articles",
        navigation_steps=NEWS_STEPS,
        output_fields=("headline", "section", "author", "published", "url"),
        target_urls=("https://www.nytimes.com/",),
        description="General news articles",
    ),
    SiteTemplate(
        site_id="bbc",
        name="BBC",
        domains=("bbc.com", "bbc.co.uk"),
        aliases=("bbc", "bbc news"),
        extraction_goal="news_articles",
        navigation_steps=NEWS_STEPS,
        output_fields=("headline", "section", "published", "url"),
        target_urls=("https://www.bbc.com/news",),
        description="Global news coverage",
    ),
    SiteTemplate(
        site_id="cnn",
        name="CNN",
        domains=("cnn.com",),
        aliases=("cnn", "cnn news"),
        extraction_goal="news_articles",
        navigation_steps=NEWS_STEPS,
        output_fields=("headline", "section", "published", "url"),
        target_urls=("https://www.cnn.com/",),
        description="General news feed",
    ),
    SiteTemplate(
        site_id="reuters",
        name="Reuters",
        domains=("reuters.com",),
        aliases=("reuters",),
        extraction_goal="news_articles",
        navigation_steps=NEWS_STEPS,
        output_fields=("headline", "category", "published", "url"),
        target_urls=("https://www.reuters.com/world/",),
        description="Wire-service news feed",
    ),
    SiteTemplate(
        site_id="bloomberg",
        name="Bloomberg",
        domains=("bloomberg.com",),
        aliases=("bloomberg", "markets"),
        extraction_goal="market_news",
        navigation_steps=NEWS_STEPS,
        output_fields=("headline", "section", "published", "url"),
        target_urls=("https://www.bloomberg.com/markets",),
        description="Finance and market news",
    ),
    SiteTemplate(
        site_id="coinmarketcap",
        name="CoinMarketCap",
        domains=("coinmarketcap.com",),
        aliases=("coinmarketcap", "crypto prices"),
        extraction_goal="crypto_assets",
        navigation_steps=DOC_STEPS,
        output_fields=("asset", "price", "market_cap", "volume_24h", "url"),
        target_urls=("https://coinmarketcap.com/",),
        description="Cryptocurrency market data",
    ),
    SiteTemplate(
        site_id="coindesk",
        name="CoinDesk",
        domains=("coindesk.com",),
        aliases=("coindesk", "crypto news"),
        extraction_goal="crypto_news",
        navigation_steps=NEWS_STEPS,
        output_fields=("headline", "author", "published", "url"),
        target_urls=("https://www.coindesk.com/",),
        description="Cryptocurrency news",
    ),
    SiteTemplate(
        site_id="investopedia",
        name="Investopedia",
        domains=("investopedia.com",),
        aliases=("investopedia", "finance education"),
        extraction_goal="financial_articles",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "author", "updated", "topic", "url"),
        target_urls=("https://www.investopedia.com/",),
        description="Finance learning articles",
    ),
    SiteTemplate(
        site_id="googlescholar",
        name="Google Scholar",
        domains=("scholar.google.com",),
        aliases=("google scholar", "scholar"),
        extraction_goal="scholarly_results",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "authors", "year", "citations", "url"),
        target_urls=("https://scholar.google.com/",),
        description="Scholarly paper search results",
    ),
    SiteTemplate(
        site_id="gitlab",
        name="GitLab",
        domains=("gitlab.com",),
        aliases=("gitlab", "merge requests"),
        extraction_goal="repositories",
        navigation_steps=DOC_STEPS,
        output_fields=("project", "stars", "forks", "last_activity", "url"),
        target_urls=("https://gitlab.com/explore",),
        description="Git repository projects and activity",
    ),
    SiteTemplate(
        site_id="bitbucket",
        name="Bitbucket",
        domains=("bitbucket.org",),
        aliases=("bitbucket", "repos"),
        extraction_goal="repositories",
        navigation_steps=DOC_STEPS,
        output_fields=("project", "owner", "updated", "url"),
        target_urls=("https://bitbucket.org/product",),
        description="Repository and workspace metadata",
    ),
    SiteTemplate(
        site_id="amazon",
        name="Amazon",
        domains=("amazon.com", "amazon.in", "amazon.co.uk"),
        aliases=("amazon", "products", "shopping"),
        extraction_goal="products",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "price", "rating", "reviews", "url"),
        target_urls=("https://www.amazon.com/gp/bestsellers",),
        description="Ecommerce product listings",
    ),
    SiteTemplate(
        site_id="ebay",
        name="eBay",
        domains=("ebay.com",),
        aliases=("ebay", "auctions"),
        extraction_goal="products",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "price", "condition", "shipping", "url"),
        target_urls=("https://www.ebay.com/deals",),
        description="Auction and product cards",
    ),
    SiteTemplate(
        site_id="walmart",
        name="Walmart",
        domains=("walmart.com",),
        aliases=("walmart", "shopping"),
        extraction_goal="products",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "price", "rating", "availability", "url"),
        target_urls=("https://www.walmart.com/shop/deals",),
        description="Retail product listings",
    ),
    SiteTemplate(
        site_id="etsy",
        name="Etsy",
        domains=("etsy.com",),
        aliases=("etsy", "handmade"),
        extraction_goal="products",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "price", "shop", "rating", "url"),
        target_urls=("https://www.etsy.com/c/jewelry",),
        description="Marketplace products and shops",
    ),
    SiteTemplate(
        site_id="aliexpress",
        name="AliExpress",
        domains=("aliexpress.com",),
        aliases=("aliexpress", "marketplace"),
        extraction_goal="products",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "price", "orders", "shipping", "url"),
        target_urls=("https://www.aliexpress.com/category/200003482/electronics.html",),
        description="Marketplace product listings",
    ),
    SiteTemplate(
        site_id="coursera",
        name="Coursera",
        domains=("coursera.org",),
        aliases=("coursera", "courses"),
        extraction_goal="courses",
        navigation_steps=DOC_STEPS,
        output_fields=("course", "provider", "rating", "level", "url"),
        target_urls=("https://www.coursera.org/courses",),
        description="Course catalog extraction",
    ),
    SiteTemplate(
        site_id="udemy",
        name="Udemy",
        domains=("udemy.com",),
        aliases=("udemy", "courses"),
        extraction_goal="courses",
        navigation_steps=DOC_STEPS,
        output_fields=("course", "instructor", "rating", "price", "url"),
        target_urls=("https://www.udemy.com/courses/development/",),
        description="Course marketplace extraction",
    ),
    SiteTemplate(
        site_id="edx",
        name="edX",
        domains=("edx.org",),
        aliases=("edx", "courses"),
        extraction_goal="courses",
        navigation_steps=DOC_STEPS,
        output_fields=("course", "institution", "duration", "level", "url"),
        target_urls=("https://www.edx.org/search",),
        description="Education course listings",
    ),
    SiteTemplate(
        site_id="freecodecamp",
        name="freeCodeCamp",
        domains=("freecodecamp.org",),
        aliases=("freecodecamp", "curriculum"),
        extraction_goal="learning_resources",
        navigation_steps=DOC_STEPS,
        output_fields=("resource", "category", "difficulty", "url"),
        target_urls=("https://www.freecodecamp.org/news/",),
        description="Learning resources and tutorials",
    ),
    SiteTemplate(
        site_id="paperswithcode",
        name="Papers with Code",
        domains=("paperswithcode.com",),
        aliases=("paperswithcode", "benchmarks"),
        extraction_goal="papers_and_models",
        navigation_steps=DOC_STEPS,
        output_fields=("paper", "task", "sota_metric", "code_link", "url"),
        target_urls=("https://paperswithcode.com/sota",),
        description="ML paper and benchmark extraction",
    ),
    SiteTemplate(
        site_id="openreview",
        name="OpenReview",
        domains=("openreview.net",),
        aliases=("openreview", "conference papers"),
        extraction_goal="conference_papers",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "authors", "venue", "rating", "url"),
        target_urls=("https://openreview.net/group?id=ICLR.cc",),
        description="Conference paper pages and metadata",
    ),
    SiteTemplate(
        site_id="leetcode",
        name="LeetCode",
        domains=("leetcode.com",),
        aliases=("leetcode", "problems"),
        extraction_goal="coding_problems",
        navigation_steps=DOC_STEPS,
        output_fields=("problem", "difficulty", "acceptance", "tags", "url"),
        target_urls=("https://leetcode.com/problemset/",),
        description="Coding challenge listings",
    ),
    SiteTemplate(
        site_id="geeksforgeeks",
        name="GeeksforGeeks",
        domains=("geeksforgeeks.org",),
        aliases=("geeksforgeeks", "gfg"),
        extraction_goal="tutorials",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "topic", "difficulty", "url"),
        target_urls=("https://www.geeksforgeeks.org/explore",),
        description="Tutorial and practice resources",
    ),
    SiteTemplate(
        site_id="indeed",
        name="Indeed",
        domains=("indeed.com",),
        aliases=("indeed", "job listings"),
        extraction_goal="jobs",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "company", "location", "salary", "url"),
        target_urls=("https://www.indeed.com/jobs",),
        description="Job listing extraction",
    ),
    SiteTemplate(
        site_id="glassdoor",
        name="Glassdoor",
        domains=("glassdoor.com",),
        aliases=("glassdoor", "company reviews"),
        extraction_goal="jobs_and_companies",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "company", "rating", "location", "url"),
        target_urls=("https://www.glassdoor.com/Job/index.htm",),
        description="Jobs and company review listings",
    ),
    SiteTemplate(
        site_id="twitch",
        name="Twitch",
        domains=("twitch.tv",),
        aliases=("twitch", "streams"),
        extraction_goal="live_streams",
        navigation_steps=SOCIAL_STEPS,
        output_fields=("streamer", "title", "viewers", "category", "url"),
        target_urls=("https://www.twitch.tv/directory",),
        description="Live stream directory extraction",
    ),
    SiteTemplate(
        site_id="vimeo",
        name="Vimeo",
        domains=("vimeo.com",),
        aliases=("vimeo", "videos"),
        extraction_goal="videos",
        navigation_steps=SOCIAL_STEPS,
        output_fields=("title", "creator", "plays", "likes", "url"),
        target_urls=("https://vimeo.com/channels",),
        description="Video channel discovery",
    ),
    SiteTemplate(
        site_id="spotify",
        name="Spotify",
        domains=("spotify.com", "open.spotify.com"),
        aliases=("spotify", "playlists"),
        extraction_goal="music_catalog",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "type", "creator", "followers", "url"),
        target_urls=("https://open.spotify.com/genre/0JQ5DAqbMKFEC4WFtoNRpw",),
        description="Music and playlist metadata",
    ),
    SiteTemplate(
        site_id="soundcloud",
        name="SoundCloud",
        domains=("soundcloud.com",),
        aliases=("soundcloud", "tracks"),
        extraction_goal="audio_tracks",
        navigation_steps=SOCIAL_STEPS,
        output_fields=("title", "artist", "plays", "likes", "url"),
        target_urls=("https://soundcloud.com/discover",),
        description="Audio track discovery",
    ),
    SiteTemplate(
        site_id="airbnb",
        name="Airbnb",
        domains=("airbnb.com",),
        aliases=("airbnb", "stays"),
        extraction_goal="listings",
        navigation_steps=DOC_STEPS,
        output_fields=("title", "location", "price_per_night", "rating", "url"),
        target_urls=("https://www.airbnb.com/s/homes",),
        description="Accommodation listings",
    ),
    SiteTemplate(
        site_id="booking",
        name="Booking.com",
        domains=("booking.com",),
        aliases=("booking", "hotels"),
        extraction_goal="hotel_listings",
        navigation_steps=DOC_STEPS,
        output_fields=("hotel", "location", "price", "rating", "url"),
        target_urls=("https://www.booking.com/",),
        description="Hotel search and listing extraction",
    ),
    SiteTemplate(
        site_id="zillow",
        name="Zillow",
        domains=("zillow.com",),
        aliases=("zillow", "real estate"),
        extraction_goal="property_listings",
        navigation_steps=DOC_STEPS,
        output_fields=("address", "price", "beds", "baths", "url"),
        target_urls=("https://www.zillow.com/homes/",),
        description="Property listing extraction",
    ),
)
